django_ac22/apps/ac22/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from apps.usuarios.views import login_view, dashboard_view
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login_view, name="view_login"),
    url(r'^dashboard/$', dashboard_view, name="dashboard"),
    url(r'^usuarios/', include('apps.usuarios.urls')),
    url(r'^directorio/', include('apps.directorio.urls')),
    url(r'^avisos/', include('apps.avisos.urls')),
    url(r'^inventario/', include('apps.inventario.urls')),
    url(r'^obra/', include('apps.obras.urls')),
    url(r'^obra/especificaciones/', include('apps.especificaciones.urls')),
    url(r'^obra/propuesta_economica/', include('apps.propuesta_economica.urls')),
    url(r'^obra/propuesta_tecnica/', include('apps.propuesta_tecnica.urls')),
    url(r'^ingenieria/memorias/', include('apps.memorias.urls')),
    url(r'^ingenieria/proyecto_ejecutivo/', include('apps.proyecto_ejecutivo.urls')),
    url(r'^ingenieria/calculos/', include('apps.calculos.urls')),
    url(r'^ejecucion/programa_gral_de_obras/', include('apps.programa_gral_de_obras.urls')),
    url(r'^ejecucion/suministros/', include('apps.suministros.urls')),
    url(r'^ejecucion/seguimiento/', include('apps.seguimiento.urls')),
    url(r'^ejecucion/estimaciones/', include('apps.estimaciones.urls')),
    url(r'^recursos/', include('apps.recursos.urls')),
    url(r'^catalogo_de_conceptos/', include('apps.catalogo_de_conceptos.urls')),
    url(r'^gestion_financiera/', include('apps.gestion_financiera.urls')),
    url(r'^proveedores/', include('apps.proveedores.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_ac22/apps/directorio/urls.py
from django.conf.urls import  include, url
from django.conf.urls.static import static
from apps.directorio import views as directorio_view

urlpatterns = [
	url(r'^$', directorio_view.directorio_view, name="vista_directorio"),
]
 

django_ac22/apps/directorio/models.py
import datetime 
from django.db import models
from django.contrib.auth.models import User

class EntidadCategoria(models.Model):
  nombre = models.CharField(
    max_length=450,
  )
  descripcion = models.TextField()
  fecha_creacion =  models.DateTimeField(editable=False)
  fecha_modificacion =  models.DateTimeField(editable=False)
  def __str__(self):
    return self.nombre
  def save(self, *args, **kwargs):
    ''' On save, update timestamps '''
    if not self.id:
      self.fecha_creacion = datetime.datetime.today()
    self.fecha_modificacion = datetime.datetime.today()
    super(EntidadCategoria, self).save(*args, **kwargs)


class Entidad(models.Model):
  usuario_creo = models.ForeignKey(
    User
  )
  nombre = models.CharField(
    max_length=450
  )
  telefono = models.CharField(
    max_length=450
  )
  correo = models.EmailField(
  )
  pagina_web = models.CharField(
    max_length=450
  )
  categoria = models.ForeignKey(
    EntidadCategoria
  )
  ubicacion = models.TextField()
  fecha_creacion =  models.DateTimeField(editable=False)
  fecha_modificacion =  models.DateTimeField(editable=False)

  def save(self, *args, **kwargs):
    ''' On save, update timestamps '''
    if not self.id:
      self.fecha_creacion = datetime.datetime.today()
    self.fecha_modificacion = datetime.datetime.today()
    super(Entidad, self).save(*args, **kwargs)




django_ac22/apps/directorio/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate
from django.forms.widgets import Select, Textarea
from apps.directorio.models import Entidad, EntidadCategoria

class EntidadAddForm(forms.ModelForm):
  nombre = forms.CharField(
    widget=forms.TextInput(
      attrs={
        'class': 'form-control',
        'placeholder' : 'Ingresa el nombre de la Entidad',
      }
    ), 
    label = "Nombre de la entidad",
  )
  telefono = forms.CharField(
    widget=forms.TextInput(
      attrs={
        'class': 'form-control',
        'placeholder' : 'Ingresa el telefono',
      }
    ), 
    label = "Telefono",
  )
  correo = forms.CharField(
    widget=forms.TextInput(
      attrs={
        'class': 'form-control',
        'placeholder' : 'Ingresa el correo',
      }
    ), 
    label = "Correo electronico",
    required=False,
  )
  pagina_web = forms.CharField(
    widget=forms.TextInput(
      attrs={
        'class': 'form-control',
        'placeholder' : 'Ingresa la pagina web',
      }
    ), 
    label = "Pagina web",
    required=False,
  )
  ubicacion = forms.CharField(
    widget=forms.Textarea(
      attrs={
          'class': 'form-control',
          'rows' : '8',
          'placeholder' :'Ingresa la ubicacion'
        }
    ),
    required=False,
  )
  categoria = forms.ModelChoiceField(
    queryset = EntidadCategoria.objects.all(),
    widget=forms.Select(
      attrs={
        'class': 'form-control',
      }
    )
  )
  class Meta:
    model = Entidad
    fields = ('nombre','telefono', 'correo', 'pagina_web', 'ubicacion','categoria')

class EntidadCategoriaAddForm(forms.ModelForm):
  nombre = forms.CharField(
    widget=forms.TextInput(
      attrs={
        'class': 'form-control',
        'placeholder' : 'Ingresa el titulo de la encuesta',
      }
    ), 
    label = "Nombre de la entidad",
  )

  descripcion = forms.CharField(
    widget=forms.Textarea(
      attrs={
          'class': 'form-control',
          'rows' : '8',
          'placeholder' :'Ingresa la descripcion'
        }
    ),
    required=False,
  )
  class Meta:
    model = EntidadCategoria
    fields = ('nombre','descripcion',)

django_ac22/apps/directorio/views.py
# -*- encoding: utf-8 -*-
from datetime import datetime, date, time
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import permission_required, login_required
from django.http import HttpResponseRedirect, HttpResponse, Http404, HttpResponseServerError
from django.forms import formset_factory
from django.contrib.auth.models import User
from apps.directorio.forms import EntidadAddForm, EntidadCategoriaAddForm
from apps.directorio.models import EntidadCategoria

@login_required(login_url='/')
def directorio_view(request):
  usuarios_condominio = User.objects.all()
  entidad_form = EntidadAddForm(prefix='entidad')
  entidad_categoria_form = EntidadCategoriaAddForm(prefix='categoriaEntidad')
  message = ''
  if request.method == "POST":
    entidad_form = EntidadAddForm(request.POST, prefix='entidad')
    if entidad_form.is_valid():
      entidad = entidad_form.save(commit=False)
      entidad.usuario_creo = request.user
      entidad_form.save()
      entidad_form = EntidadAddForm(prefix='entidad')
      entidad_categoria_form = EntidadCategoriaAddForm(prefix='categoriaEntidad')
      message = 'Entidad gudardada correctamente'
    entidad_categoria_form = EntidadCategoriaAddForm(request.POST, prefix='categoriaEntidad')
    if entidad_categoria_form.is_valid():
      entidad_categoria_form.save()
      entidad_form = EntidadAddForm(prefix='entidad')
      entidad_categoria_form = EntidadCategoriaAddForm(prefix='categoriaEntidad')
      message = 'Categoria gudardada correctamente'
  categorias_entidad = EntidadCategoria.objects.all()
  context = {
    'usuarios_condominio' : usuarios_condominio,
    'categorias_entidad' : categorias_entidad,
    'entidad_form' : entidad_form,
    'entidad_categoria_form': entidad_categoria_form,
    'message': message
  }
  return render(request, 'directorio/directorio.html',context)

django_ac22/templates/directorio/directorio.html
{% extends "base.html" %}
{% block title %}
Directorio
{% endblock%}
{% block style %}
<link href="{{ STATIC_PREFIX }}assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="{{ STATIC_PREFIX }}assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<link href="{{ STATIC_PREFIX }}assets/global/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css" rel="stylesheet" type="text/css"/>
<link href="{{ STATIC_PREFIX }}assets/global/plugins/bootstrap-modal/css/bootstrap-modal.css" rel="stylesheet" type="text/css"/>
{% endblock%}
{% block body %}
<div class="page-content">
  <!-- BEGIN PAGE HEADER-->
  <div class="page-bar">
    <ul class="page-breadcrumb">
      <li>
        <a href="index.html">Home</a>
        <i class="fa fa-circle"></i>
      </li>
      <li>
         <span>Comunicación</span>
      </li>
    </ul>
  </div>
  
  <h3 class="page-title">
  DIRECTORIO
  </h3>
  <!-- BEGIN MODAL RESPONSIVE -->
  <div id="modal_entidad" class="modal fade" tabindex="-1" data-width="760">

    <form role="form" action="{% url 'vista_directorio' %}" method="POST" id="form_crear_directorio">
      {% csrf_token %}
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title caption-subject font-blue-madison bold uppercase">CREAR UNA NUEVA ENTIDAD</h4>
      </div>
      <div class="modal-body">
        <div class="alert alert-danger display-hide" style="display: none;">
          <button class="close" data-close="alert"></button> Tienes algunos errores. 
        </div>
        <div class="alert alert-success display-hide" style="display: none;">
                    <button class="close" data-close="alert"></button> Your form validation is successful! 
                </div>
        <div class="row">
          <div class="col-md-12">
            {% for field in entidad_form %}
            <div class="form-group">
                <label class="control-label">{{ field.label|striptags }}</label>
              {{ field }}
              <span id="url-error" class="help-block help-block-error"></span>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" data-dismiss="modal" class="btn btn-default">Cancelar</button>
        <button type="submit" class="btn blue">Enviar</button>
      </div>
    </form>
  </div>
  <!-- END MODAL RESPONSIVE -->
  <!-- BEGIN MODAL RESPONSIVE -->
  <div id=modal_categoria_entidad class="modal fade" tabindex="-1" data-width="760">

    <form role="form" action="{% url 'vista_directorio' %}" method="POST" id="">
      {% csrf_token %}
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title caption-subject font-blue-madison bold uppercase">CREAR UNA NUEVA CATEGORIA DE LAS ENTIDADES</h4>
      </div>
      <div class="modal-body">
        <div class="alert alert-danger display-hide" style="display: none;">
          <button class="close" data-close="alert"></button> Tienes algunos errores. 
        </div>
        <div class="alert alert-success display-hide" style="display: none;">
                    <button class="close" data-close="alert"></button> Your form validation is successful! 
                </div>
        <div class="row">
          <div class="col-md-12">
            {% for field in entidad_categoria_form %}
            <div class="form-group">
                <label class="control-label">{{ field.label|striptags }}</label>
              {{ field }}
              <span id="url-error" class="help-block help-block-error"></span>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" data-dismiss="modal" class="btn btn-default">Cancelar</button>
        <button type="submit" class="btn blue">Enviar</button>
      </div>
    </form>
  </div>
  <!-- END MODAL RESPONSIVE -->
    <div class="portlet light bordered">
      <div class="portlet-title tabbable-line">
        <div class="caption">
            <i class="icon-pin font-yellow-lemon"></i>
            <span class="caption-subject bold font-yellow-lemon uppercase"> DIRECTORIO </span>
        </div>
        <div class="actions">
        <div class="clearfix">
          <a class="btn  green" data-toggle="modal" href="#modal_entidad">
                Añadir nueva entidad
                <i class="fa fa-plus"></i>
            </a>
            <button data-toggle="modal" class="btn green" href="#modal_categoria_entidad">
                Añadir nueva categoria
                <i class="fa fa-plus"></i>
            </button>
          </div>
      </div>
        </div>
    <div class="portlet-body">
            <div class="tab-content">
        <div class="row">
                <div class="col-md-2 col-sm-4 col-xs-4">
                  <ul class="nav nav-tabs tabs-left">
                    {% if categorias_entidad %}
                        {% for categoria in categorias_entidad %}
                            <li >
                              <a href="#tab_{{ forloop.counter }}" data-toggle="tab">{{ categoria }}</a>
                            </li>
                        {% endfor %}
                    {% endif %}
                    <li class="active">
                       <a href="#tab_condominos" data-toggle="tab">Internos de la obra </a>
                    </li>
                  </ul>
                </div>
                <div class="col-md-10 col-sm-8 col-xs-8">
                  <div class="tab-content">
                    {% if categorias_entidad %}
                        {% for categoria in categorias_entidad %}
                      <div class="tab-pane" id="tab_{{ forloop.counter }}">
                        <!-- BEGIN EXAMPLE TABLE PORTLET-->
                      <div class="portlet light bordered">
                        <div class="portlet-body">
                          <table class="table table-striped table-bordered table-hover table-checkable order-column " id="sample_1">
                            <thead>
                              <tr>
                                <th>Entidad/Persona </th>
                                <th>Telefono(s)</th>
                                <th>Correo</th>
                                <th>Pagina web</th>
                                <th>Ubicacion</th>
                              </tr>
                            </thead>
                            <tbody>
                                {% if categoria.entidad_set.all %}
                                    {% for entidad in categoria.entidad_set.all %}
                                <tr class="odd ">
                                <td>{{ entidad.nombre }}</td>
                                <td>{{ entidad.telefono }}</td>
                                <td>
                                  <a href="mailto:{{ usuario.email }}"> {{ usuario.email }} </a>
                                </td>
                                <td>
                                    
                                </td>
                                <td class="center"> 
                                    {{ usuario.ubicacion }} 
                                </td>
                              </tr>
                                    {% endfor %}
                                {% else %}
                                <tr>
                                    <td colspan="5">No se encontraron entidades en esta categoria</td>
                                </tr>
                                {% endif %}
                            </tbody>
                          </table>
                        </div>
                      </div>
                      <!-- END EXAMPLE TABLE PORTLET-->
                      </div>
                        {% endfor %}
                    {% endif %}
                    <div class="tab-pane active" id="tab_condominos">
                        <!-- BEGIN EXAMPLE TABLE PORTLET-->
                      <div class="portlet light bordered">
                        <div class="portlet-body">
                          <table class="table table-striped table-bordered table-hover directorio" id="">
                            <thead>
                              <tr>
                                <th>Usuarios</th>
                                <th>Telefono(s)</th>
                                <th>Correo</th>
                                <th>Pagina web</th>
                                <th>Ubicacion</th>
                              </tr>
                            </thead>
                            <tbody>
                                {% for usuario in usuarios_condominio %}
                                <tr class="odd ">
                                <td> {{ usuario.first_name }} {{ usuario.last_name }}</td>
                                <td>{{ usuario.userprofile.telefono }}</td>
                                <td>
                                  <a href="mailto:{{ usuario.email }}"> {{ usuario.email }} </a>
                                </td>
                                <td>
                                    
                                </td>
                                <td class="center"> 
                                    {{ usuario.ubicacion }} 
                                </td>
                              </tr>
                                {% endfor %}
                            </tbody>
                          </table>
                        </div>
                      </div>
                      <!-- END EXAMPLE TABLE PORTLET-->
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
  <!-- END PAGE HEADER-->
  
</div>
{% endblock %}
{% block javascript %}
<!-- BEGIN PAGE LEVEL PLUGINS -->
  <script src="{{ STATIC_PREFIX }}assets/global/scripts/datatable.js" type="text/javascript"></script>
  <script src="{{ STATIC_PREFIX }}assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
  <script src="{{ STATIC_PREFIX }}assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
  <script src="{{ STATIC_PREFIX }}assets/global/plugins/bootstrap-modal/js/bootstrap-modalmanager.js" type="text/javascript"></script>
    <script src="{{ STATIC_PREFIX }}assets/global/plugins/bootstrap-modal/js/bootstrap-modal.js" type="text/javascript"></script>
    <script src="{{ STATIC_PREFIX }}assets/pages/scripts/ui-extended-modals.js"></script>
    <script src="{{ STATIC_PREFIX }}assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
  <script src="{{ STATIC_PREFIX }}assets/global/plugins/jquery-validation/js/additional-methods.min.js" type="text/javascript"></script>
  <script src="{{ STATIC_PREFIX }}js/apps/directorio/directorio.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<script>
jQuery(document).ready(function() {    
  {% for field in entidad_form %}
    {% if field.errors %}
      $('#modal_entidad').modal('show');
      toastr["error"]("{{ field.errors|striptags }}", "{{ field.label_tag|striptags }}");
    {% endif %}
  {% endfor %}
  {% if message  %}
    
    toastr["success"]("{{ message|safe }}", "Mensaje");
  {% endif %}
});
</script>
{% endblock %}